package HibFiles;
// Generated Jun 12, 2016 7:31:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private Integer idcomment;
     private Recipe recipe;
     private User user;
     private String commentDesc;
     private Date date;
     private Date time;

    public Comment() {
    }

	
    public Comment(Recipe recipe, User user) {
        this.recipe = recipe;
        this.user = user;
    }
    public Comment(Recipe recipe, User user, String commentDesc, Date date, Date time) {
       this.recipe = recipe;
       this.user = user;
       this.commentDesc = commentDesc;
       this.date = date;
       this.time = time;
    }
   
    public Integer getIdcomment() {
        return this.idcomment;
    }
    
    public void setIdcomment(Integer idcomment) {
        this.idcomment = idcomment;
    }
    public Recipe getRecipe() {
        return this.recipe;
    }
    
    public void setRecipe(Recipe recipe) {
        this.recipe = recipe;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCommentDesc() {
        return this.commentDesc;
    }
    
    public void setCommentDesc(String commentDesc) {
        this.commentDesc = commentDesc;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


