package HibFiles;
// Generated May 12, 2016 3:57:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FoodCategory generated by hbm2java
 */
public class FoodCategory  implements java.io.Serializable {


     private Integer idfoodCategory;
     private String categoryName;
     private Set<Recipe> recipes = new HashSet<Recipe>(0);

    public FoodCategory() {
    }

    public FoodCategory(String categoryName, Set<Recipe> recipes) {
       this.categoryName = categoryName;
       this.recipes = recipes;
    }
   
    public Integer getIdfoodCategory() {
        return this.idfoodCategory;
    }
    
    public void setIdfoodCategory(Integer idfoodCategory) {
        this.idfoodCategory = idfoodCategory;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Set<Recipe> getRecipes() {
        return this.recipes;
    }
    
    public void setRecipes(Set<Recipe> recipes) {
        this.recipes = recipes;
    }




}


