package HibFiles;
// Generated May 1, 2016 1:44:28 AM by Hibernate Tools 4.3.1



/**
 * Image generated by hbm2java
 */
public class Image  implements java.io.Serializable {


     private Integer idimage;
     private Recipe recipe;
     private byte[] imageData;

    public Image() {
    }

	
    public Image(Recipe recipe) {
        this.recipe = recipe;
    }
    public Image(Recipe recipe, byte[] imageData) {
       this.recipe = recipe;
       this.imageData = imageData;
    }
   
    public Integer getIdimage() {
        return this.idimage;
    }
    
    public void setIdimage(Integer idimage) {
        this.idimage = idimage;
    }
    public Recipe getRecipe() {
        return this.recipe;
    }
    
    public void setRecipe(Recipe recipe) {
        this.recipe = recipe;
    }
    public byte[] getImageData() {
        return this.imageData;
    }
    
    public void setImageData(byte[] imageData) {
        this.imageData = imageData;
    }




}


