package HibFiles;
// Generated Jun 15, 2016 6:41:39 PM by Hibernate Tools 4.3.1



/**
 * MyIngredient generated by hbm2java
 */
public class MyIngredient  implements java.io.Serializable {


     private Integer idingredientHasUser;
     private Ingredient ingredient;
     private User user;

    public MyIngredient() {
    }

    public MyIngredient(Ingredient ingredient, User user) {
       this.ingredient = ingredient;
       this.user = user;
    }
   
    public Integer getIdingredientHasUser() {
        return this.idingredientHasUser;
    }
    
    public void setIdingredientHasUser(Integer idingredientHasUser) {
        this.idingredientHasUser = idingredientHasUser;
    }
    public Ingredient getIngredient() {
        return this.ingredient;
    }
    
    public void setIngredient(Ingredient ingredient) {
        this.ingredient = ingredient;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


