package HibFiles;
// Generated Jun 15, 2016 6:41:39 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Request generated by hbm2java
 */
public class Request  implements java.io.Serializable {


     private Integer idrequest;
     private User user;
     private String recipeName;
     private Date date;
     private String status;

    public Request() {
    }

	
    public Request(User user) {
        this.user = user;
    }
    public Request(User user, String recipeName, Date date, String status) {
       this.user = user;
       this.recipeName = recipeName;
       this.date = date;
       this.status = status;
    }
   
    public Integer getIdrequest() {
        return this.idrequest;
    }
    
    public void setIdrequest(Integer idrequest) {
        this.idrequest = idrequest;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getRecipeName() {
        return this.recipeName;
    }
    
    public void setRecipeName(String recipeName) {
        this.recipeName = recipeName;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


