package HibFiles;
// Generated May 12, 2016 3:57:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Unit generated by hbm2java
 */
public class Unit  implements java.io.Serializable {


     private Integer idunit;
     private String name;
     private Set<RecipeHasIngredient> recipeHasIngredients = new HashSet<RecipeHasIngredient>(0);

    public Unit() {
    }

    public Unit(String name, Set<RecipeHasIngredient> recipeHasIngredients) {
       this.name = name;
       this.recipeHasIngredients = recipeHasIngredients;
    }
   
    public Integer getIdunit() {
        return this.idunit;
    }
    
    public void setIdunit(Integer idunit) {
        this.idunit = idunit;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<RecipeHasIngredient> getRecipeHasIngredients() {
        return this.recipeHasIngredients;
    }
    
    public void setRecipeHasIngredients(Set<RecipeHasIngredient> recipeHasIngredients) {
        this.recipeHasIngredients = recipeHasIngredients;
    }




}


