package HibFiles;
// Generated May 1, 2016 11:31:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private UserType userType;
     private String fname;
     private String lname;
     private String mobile;
     private String address;
     private Date registerDate;
     private Set<Comment> comments = new HashSet<Comment>(0);
     private Set<Recipe> recipes = new HashSet<Recipe>(0);
     private Set<UserLogin> userLogins = new HashSet<UserLogin>(0);
     private Set<Notification> notifications = new HashSet<Notification>(0);
     private Set<Rating> ratings = new HashSet<Rating>(0);

    public User() {
    }

	
    public User(UserType userType) {
        this.userType = userType;
    }
    public User(UserType userType, String fname, String lname, String mobile, String address, Date registerDate, Set<Comment> comments, Set<Recipe> recipes, Set<UserLogin> userLogins, Set<Notification> notifications, Set<Rating> ratings) {
       this.userType = userType;
       this.fname = fname;
       this.lname = lname;
       this.mobile = mobile;
       this.address = address;
       this.registerDate = registerDate;
       this.comments = comments;
       this.recipes = recipes;
       this.userLogins = userLogins;
       this.notifications = notifications;
       this.ratings = ratings;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Date getRegisterDate() {
        return this.registerDate;
    }
    
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }
    public Set<Recipe> getRecipes() {
        return this.recipes;
    }
    
    public void setRecipes(Set<Recipe> recipes) {
        this.recipes = recipes;
    }
    public Set<UserLogin> getUserLogins() {
        return this.userLogins;
    }
    
    public void setUserLogins(Set<UserLogin> userLogins) {
        this.userLogins = userLogins;
    }
    public Set<Notification> getNotifications() {
        return this.notifications;
    }
    
    public void setNotifications(Set<Notification> notifications) {
        this.notifications = notifications;
    }
    public Set<Rating> getRatings() {
        return this.ratings;
    }
    
    public void setRatings(Set<Rating> ratings) {
        this.ratings = ratings;
    }




}


